[parameters]
Xlcomp = { nominal = 1.0, min = 0.95, max = 1.05, corners = true, include = true }
Xjcomp = { nominal = 1.0, min = 0.95, max = 1.05, corners = true, include = true }
Xac = { nominal = 1.0, min = 0.3, max = 1.7, logs = false, sig_pct = 4.0, include = true }
Xpdc = { nominal = 1.0, min = 0.3, max = 1.7, logs = false, nom_min = 1.0, nom_max = 1.0, sig_pct = 4.0, include = true }
inoff = { nominal = 0.0, min = -1.0, max = 1.0, logs = false, sigma = 0.04, include = true }
inipp = { nominal = 1.0, min = 0.0, max = 3.0, logs = false, sigma = 0.04, include = true }
b0 = { nominal = 0.08, min = 0.03, max = 0.3, sig_pct = 4.0, include = true }
l0 = { nominal = 5.0, min = 1.5, max = 15.0, sig_pct = 4.0, include = true }
b1 = { nominal = 0.018, min = 0.006, max = 0.06, sig_pct = 4.0, include = false }
b2 = { nominal = 0.07, min = 0.02, max = 0.2, sig_pct = 4.0, include = false }
b34 = { nominal = 0.04, min = 0.012, max = 0.12, sig_pct = 4.0, include = false }
l45 = { nominal = 30.0, min = 10.0, max = 100.0, sig_pct = 4.0, include = false }
